--------------------------------------------------------
--  File created - wtorek-maja-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHARGES
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."CHARGES" 
   (	"ID" NUMBER, 
	"AMOUNT" FLOAT(126), 
	"WATCHID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."CUSTOMERS" 
   (	"ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"DISCOUNTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DISCOUNTS
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."DISCOUNTS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"AMOUNT" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENTRANCEMETHOD
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."ENTRANCEMETHOD" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENTRANCES
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."ENTRANCES" 
   (	"ID" NUMBER, 
	"WATCHID" NUMBER, 
	"ENTRANCEMETHODID" NUMBER, 
	"TIME" DATE, 
	"CUSTOMERID" NUMBER(1,0), 
	"HOURS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXITS
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."EXITS" 
   (	"ID" NUMBER, 
	"WATCHID" NUMBER, 
	"TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."SERVICES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(60 BYTE), 
	"PRICEPERHOUR" NUMBER, 
	"PRICEPERMINUTE" NUMBER, 
	"ENTRANCEMETHODID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."TRANSACTIONS" 
   (	"ID" NUMBER, 
	"SERVICEID" NUMBER, 
	"TRANSACTIONTYPEID" NUMBER, 
	"WATCHID" NUMBER, 
	"TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONTYPES
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."TRANSACTIONTYPES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VISITS
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."VISITS" 
   (	"ID" NUMBER(*,0), 
	"WATCHID" NUMBER(*,0), 
	"CUSTOMERID" NUMBER(*,0), 
	"SERVICEID" NUMBER(*,0), 
	"EXITPAYMENT" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WATCHES
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."WATCHES" 
   (	"ID" NUMBER, 
	"CUSTOMERID" NUMBER, 
	"SERVICEID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into AQUAPARK.CHARGES
SET DEFINE OFF;
REM INSERTING into AQUAPARK.CUSTOMERS
SET DEFINE OFF;
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('1','Jakub','Zatoñ','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('2','Tomasz','Zawadzki','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('3','Michal','Kaminski','2');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('4','Janek','Dziecinny','3');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('6','Aleksandra ','Uliasz','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('7','dasdas','dasdas','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('9','siema','tu kapucha','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('10','sieema','elo','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('11','siema','elo','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('12','siema','elo','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('8','da','dsa','1');
Insert into AQUAPARK.CUSTOMERS (ID,FIRSTNAME,LASTNAME,DISCOUNTID) values ('5','kox','wchodzi','1');
REM INSERTING into AQUAPARK.DISCOUNTS
SET DEFINE OFF;
Insert into AQUAPARK.DISCOUNTS (ID,NAME,AMOUNT) values ('1','STUDENT','0,5');
Insert into AQUAPARK.DISCOUNTS (ID,NAME,AMOUNT) values ('2','EMPLOYEE','0,3');
Insert into AQUAPARK.DISCOUNTS (ID,NAME,AMOUNT) values ('3','MINOR','0,7');
REM INSERTING into AQUAPARK.ENTRANCEMETHOD
SET DEFINE OFF;
Insert into AQUAPARK.ENTRANCEMETHOD (ID,NAME) values ('1','CASH');
REM INSERTING into AQUAPARK.ENTRANCES
SET DEFINE OFF;
REM INSERTING into AQUAPARK.EXITS
SET DEFINE OFF;
REM INSERTING into AQUAPARK.SERVICES
SET DEFINE OFF;
Insert into AQUAPARK.SERVICES (ID,NAME,PRICEPERHOUR,PRICEPERMINUTE,ENTRANCEMETHODID) values ('1','BASEN','12','1','1');
REM INSERTING into AQUAPARK.TRANSACTIONS
SET DEFINE OFF;
REM INSERTING into AQUAPARK.TRANSACTIONTYPES
SET DEFINE OFF;
REM INSERTING into AQUAPARK.VISITS
SET DEFINE OFF;
REM INSERTING into AQUAPARK.WATCHES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CHARGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."CHARGE_PK" ON "AQUAPARK"."CHARGES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."CUSTOMERS_PK" ON "AQUAPARK"."CUSTOMERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTRANCEMETHOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."ENTRANCEMETHOD_PK" ON "AQUAPARK"."ENTRANCEMETHOD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTRANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."ENTRANCE_PK" ON "AQUAPARK"."ENTRANCES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."EXIT_PK" ON "AQUAPARK"."EXITS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."SERVICES_PK" ON "AQUAPARK"."SERVICES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."TABLE1_PK" ON "AQUAPARK"."DISCOUNTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTIONTYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."TRANSACTIONTYPE_PK" ON "AQUAPARK"."TRANSACTIONTYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."TRANSACTION_PK" ON "AQUAPARK"."TRANSACTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VISITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."VISITS_PK" ON "AQUAPARK"."VISITS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."WATCH_PK" ON "AQUAPARK"."WATCHES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."TRANSACTIONS" ADD CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AQUAPARK"."TRANSACTIONS" MODIFY ("SERVICEID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."TRANSACTIONS" MODIFY ("TRANSACTIONTYPEID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."TRANSACTIONS" MODIFY ("WATCHID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."TRANSACTIONS" MODIFY ("TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTRANCEMETHOD
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."ENTRANCEMETHOD" ADD CONSTRAINT "ENTRANCEMETHOD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AQUAPARK"."ENTRANCEMETHOD" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."SERVICES" ADD CONSTRAINT "SERVICES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AQUAPARK"."SERVICES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."SERVICES" MODIFY ("PRICEPERHOUR" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."SERVICES" MODIFY ("PRICEPERMINUTE" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."SERVICES" MODIFY ("ENTRANCEMETHODID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."CUSTOMERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."CUSTOMERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."CUSTOMERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VISITS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."VISITS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."VISITS" MODIFY ("WATCHID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."VISITS" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."VISITS" MODIFY ("SERVICEID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."VISITS" ADD CONSTRAINT "VISITS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHARGES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."CHARGES" ADD CONSTRAINT "CHARGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AQUAPARK"."CHARGES" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."CHARGES" MODIFY ("WATCHID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISCOUNTS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."DISCOUNTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."DISCOUNTS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."DISCOUNTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."DISCOUNTS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONTYPES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."TRANSACTIONTYPES" ADD CONSTRAINT "TRANSACTIONTYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AQUAPARK"."TRANSACTIONTYPES" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTRANCES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."ENTRANCES" ADD CONSTRAINT "ENTRANCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AQUAPARK"."ENTRANCES" MODIFY ("WATCHID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."ENTRANCES" MODIFY ("ENTRANCEMETHODID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."ENTRANCES" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."ENTRANCES" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."ENTRANCES" MODIFY ("HOURS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXITS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."EXITS" ADD CONSTRAINT "EXIT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AQUAPARK"."EXITS" MODIFY ("WATCHID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."EXITS" MODIFY ("TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WATCHES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."WATCHES" ADD CONSTRAINT "WATCH_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AQUAPARK"."WATCHES" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."WATCHES" MODIFY ("SERVICEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CHARGES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."CHARGES" ADD CONSTRAINT "WATCHID" FOREIGN KEY ("WATCHID")
	  REFERENCES "AQUAPARK"."WATCHES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."CUSTOMERS" ADD CONSTRAINT "DISCOUNTID" FOREIGN KEY ("DISCOUNTID")
	  REFERENCES "AQUAPARK"."DISCOUNTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENTRANCES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."ENTRANCES" ADD CONSTRAINT "FK_ENTRANCEMETHODID" FOREIGN KEY ("ENTRANCEMETHODID")
	  REFERENCES "AQUAPARK"."ENTRANCEMETHOD" ("ID") ENABLE;
  ALTER TABLE "AQUAPARK"."ENTRANCES" ADD CONSTRAINT "FK_WATCHID_ENTRANCE" FOREIGN KEY ("WATCHID")
	  REFERENCES "AQUAPARK"."WATCHES" ("ID") ENABLE;
  ALTER TABLE "AQUAPARK"."ENTRANCES" ADD CONSTRAINT "CUSTOMERID" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "AQUAPARK"."CUSTOMERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXITS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."EXITS" ADD CONSTRAINT "FK_WATCHID_EXIT" FOREIGN KEY ("WATCHID")
	  REFERENCES "AQUAPARK"."WATCHES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."SERVICES" ADD CONSTRAINT "ENMETID" FOREIGN KEY ("ENTRANCEMETHODID")
	  REFERENCES "AQUAPARK"."ENTRANCEMETHOD" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."TRANSACTIONS" ADD CONSTRAINT "FK_TRANSACTIONTYPEID" FOREIGN KEY ("TRANSACTIONTYPEID")
	  REFERENCES "AQUAPARK"."TRANSACTIONTYPES" ("ID") ENABLE;
  ALTER TABLE "AQUAPARK"."TRANSACTIONS" ADD CONSTRAINT "FK_SERVICEID" FOREIGN KEY ("SERVICEID")
	  REFERENCES "AQUAPARK"."SERVICES" ("ID") ENABLE;
  ALTER TABLE "AQUAPARK"."TRANSACTIONS" ADD CONSTRAINT "FK_WATCHID" FOREIGN KEY ("WATCHID")
	  REFERENCES "AQUAPARK"."WATCHES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VISITS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."VISITS" ADD CONSTRAINT "WID" FOREIGN KEY ("WATCHID")
	  REFERENCES "AQUAPARK"."WATCHES" ("ID") ENABLE;
  ALTER TABLE "AQUAPARK"."VISITS" ADD CONSTRAINT "CID" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "AQUAPARK"."CUSTOMERS" ("ID") ENABLE;
  ALTER TABLE "AQUAPARK"."VISITS" ADD CONSTRAINT "SID" FOREIGN KEY ("SERVICEID")
	  REFERENCES "AQUAPARK"."SERVICES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WATCHES
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."WATCHES" ADD CONSTRAINT "FK_SERVICEID_WATCH" FOREIGN KEY ("SERVICEID")
	  REFERENCES "AQUAPARK"."SERVICES" ("ID") ENABLE;
