--------------------------------------------------------
--  File created - sobota-marca-21-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISCOUNTS
--------------------------------------------------------

  CREATE TABLE "AQUAPARK"."DISCOUNTS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"COLUMN3" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AQUAPARK.DISCOUNTS
SET DEFINE OFF;
Insert into AQUAPARK.DISCOUNTS (ID,NAME,COLUMN3) values ('1','STUDENT','0,5');
Insert into AQUAPARK.DISCOUNTS (ID,NAME,COLUMN3) values ('2','EMPLOYEE','0,3');
Insert into AQUAPARK.DISCOUNTS (ID,NAME,COLUMN3) values ('3','MINOR','0,7');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AQUAPARK"."TABLE1_PK" ON "AQUAPARK"."DISCOUNTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DISCOUNTS
--------------------------------------------------------

  ALTER TABLE "AQUAPARK"."DISCOUNTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."DISCOUNTS" MODIFY ("COLUMN3" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."DISCOUNTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AQUAPARK"."DISCOUNTS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
